image kin_02:
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/2.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/1.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
    .05
    "/sprites/kin/[kin_pose]/[kin_face]/0.png"
