# TODO: Translation updated at 2023-07-05 15:54

translate English strings:

    # game/core/options.rpy:15
    old "Umineko When They Cry Zero ~Waltz of Reflections and Delusions~"
    new "Umineko When They Cry Zero ~Waltz of Reflections and Delusions~"

    # game/core/options.rpy:32
    old "Developed by Jaybe Games\n\n\n\nCREATIVE DIRECTOR\n\n\n\nJaybe\n\n\n\nSTORY & SCRIPT\n\n\n\nJaybe\n\n\n\nANIMATIONS & EFFECTS\n\n\n\nJaybe from original assets\n\n\n\nCLOSED TESTER / PROOFREADER\n\n\n\nSingularity\n\nFakuum\n\nSurfingJeorn\n\nAlexHD199\n\nAiylaChan\n\nArarara555\n\nBucky\n\n\n\nADDITIONAL SPRITES\n\n\n\nAyato / Lord Zero: SurfingJeorn\n\nYuria (School Sprite): Jaybe\n\n\n\nUSED ASSETS\n\n\n\nGameassets from Umineko no Naku Koro ni Saku ~Symphony of Catbox and Dreams~\n\n\n\nDiscord Rich Presence: Lezalith\n\nFancyText: yukinogatari\n\nRPY-VNBE Achievement System: rjscdev\n\nRenPy Universal Player: GangstaKingofSA\n\nRenPyParticles: AgentAlpha81\n\nGradient Tags: sodara9\n\n\n\nMUSICBOX ORANGE\n\n\n\nBlack Lilliana Orchestra by Pennoink\n\nfullendrecharger by Rolli B\n\n\n\nUmineko ~Rose Crimson~\n\n\n\nPitiful Sneerer\n\n\n\nOPENING SONG\n\n\n\nGold Dream Symphony\n\nOriginal Performer: Kino Nei, Luck-Ganriki, dai\n\nGerman Vocals & Lyrics: aFlowerSmiles\n\nOpeningvideo: Jaybe\n\n\n\nENDING SONG\n\n\n\nGolden Sneers ~ Lovely Banquet\n\nComposed by: Luck Ganriki\n\nArranged by: Yoshitaka Hirota\n\nLyrics by: Tomoko Shinoda\n\nVocals by: Akiko Shikata\n\nAll Instruments: Yoshitaka Hirota"
    new "Developed by Jaybe Games\n\n\n\nCREATIVE DIRECTOR\n\n\n\nJaybe\n\n\n\nSTORY & SCRIPT\n\n\n\nJaybe\n\n\n\nANIMATIONS & EFFECTS\n\n\n\nJaybe from original assets\n\n\n\nCLOSED TESTER / PROOFREADER\n\n\n\nSingularity\n\nFakuum\n\nSurfingJeorn\n\nAlexHD199\n\nAiylaChan\n\nArarara555\n\nBucky\n\n\n\nADDITIONAL SPRITES\n\n\n\nAyato / Lord Zero: SurfingJeorn\n\nYuria (School Sprite): Jaybe\n\n\n\nUSED ASSETS\n\n\n\nGameassets from Umineko no Naku Koro ni Saku ~Symphony of Catbox and Dreams~\n\n\n\nDiscord Rich Presence: Lezalith\n\nFancyText: yukinogatari\n\nRPY-VNBE Achievement System: rjscdev\n\nRenPy Universal Player: GangstaKingofSA\n\nRenPyParticles: AgentAlpha81\n\nGradient Tags: sodara9\n\n\n\nMUSICBOX ORANGE\n\n\n\nBlack Lilliana Orchestra by Pennoink\n\nfullendrecharger by Rolli B\n\n\n\nUmineko ~Rose Crimson~\n\n\n\nPitiful Sneerer\n\n\n\nOPENING SONG\n\n\n\nGold Dream Symphony\n\nOriginal Performer: Kino Nei, Luck-Ganriki, dai\n\nGerman Vocals & Lyrics: aFlowerSmiles\n\nOpeningvideo: Jaybe\n\n\n\nENDING SONG\n\n\n\nGolden Sneers ~ Lovely Banquet\n\nComposed by: Luck Ganriki\n\nArranged by: Yoshitaka Hirota\n\nLyrics by: Tomoko Shinoda\n\nVocals by: Akiko Shikata\n\nAll Instruments: Yoshitaka Hirota"

