define doorfade = Fade(1.0, 1.0, 2.8, color="#fff")
define doorfadeclosed = Fade(3.5, 1.0, 1.0, color="#000000")
define longfade = Fade(1.0, 1.0, 1.5, color="#fff")
define shortfade = Fade(0.5, 0.5, 0.5, color="#fff")
define longdissolve = Dissolve(1.5)
define quickgradientwipeupright = ImageDissolve("/images/masks/upright.png", 1.5, ramplen = 16)
define quickergradientwipeupright = ImageDissolve("/images/masks/upright.png", 0.5, ramplen = 12)
define gradientwipeupright = ImageDissolve("/images/masks/upright.png", 2.0, ramplen = 16)
define doorclose = ImageDissolve("/images/masks/centerblind.png", 3.5, ramplen = 32, reverse = True)
define quickgradientwiperight = ImageDissolve("/images/masks/right.bmp", 1.0, ramplen = 16)
define quickergradientwiperight = ImageDissolve("/images/masks/right.bmp", 0.5, ramplen = 16)
define gradientwiperight = ImageDissolve("/images/masks/right.png", 3.5, ramplen = 16)
define gradientwipedown = ImageDissolve("/images/masks/down.png", 1.5, ramplen = 16)
define quickgradientwipedown = ImageDissolve("/images/masks/down.png", 0.5, ramplen = 16)
define gradientwipeup = ImageDissolve("/images/masks/up.png", 2.5, ramplen = 16)
define longerdissolve = Dissolve(2.5)
define gradientcirclefade = ImageDissolve("/images/masks/circle.png", 3.5, ramplen = 16, reverse=True)
define quickgradientcirclefade = ImageDissolve("/images/masks/circle.png", 0.5, ramplen = 16, reverse=True)
define flash = Fade(.25, 0, .25, color="#fff")
define quickflash = Fade(.0, 0.5, 0.25, color="#fff")
define openfade = Fade(1.5, 2.0, 2.0, color="#fff")
define fastdissolve = Dissolve(0.2)