screen showsong():
    zorder 999999

    ## Shows current song on screen
    $ current_music = renpy.music.get_playing('music')
    if current_music is not None and current_music in music_dictionary:
        text "♪" + music_dictionary[current_music] size 40 xalign 0.05 yalign 0.01 font "fonts/AOTFShinGoProMedium.otf" outlines [ (absolute(3), "#000", absolute(0), absolute(0)) ] at songflyin, bgm_gradient
    else:
        text "" size 40 xalign 0.05 yalign 0.01 font "fonts/AOTFShinGoProMedium.otf" outlines [ (absolute(3), "#000", absolute(0), absolute(0)) ] at songflyin, bgm_gradient

    timer 8 action Hide('showsong')

default persistent.audio_cues = True

init python:

    thunberg_lily = "audio/bgm/umib_001.opus",
    door_of_summer = "audio/bgm/umib_002.opus",
    hane = "audio/bgm/umib_003.opus",
    ride_on = "audio/bgm/umib_004.opus",
    sea = "audio/bgm/umib_005.opus",
    hour_of_darkness = "audio/bgm/umib_006.opus",
    novelette = "audio/bgm/umib_007.opus",
    hope = "audio/bgm/umib_008.opus",
    white_shadow = "audio/bgm/umib_009.opus",
    steady_pace = "audio/bgm/umib_010.opus",
    towering_cloud_in_summer = "audio/bgm/umib_011.opus",
    moonlit_night = "audio/bgm/umib_012.opus",
    rose = "audio/bgm/umib_013.opus",
    at_deaths_door = "audio/bgm/umib_014.opus",
    hells_halls = "audio/bgm/umib_015.opus",
    fortitude = "audio/bgm/umib_016.opus",
    witch_in_gold_cembalo = "audio/bgm/umib_017.opus",
    beckoning = "audio/bgm/umib_018.opus",
    fishy_aroma = "audio/bgm/umib_019.opus",
    stupefaction = "audio/bgm/umib_020.opus",
    praise = "audio/bgm/umib_021.opus",
    _pass = "audio/bgm/umib_022.opus",
    butterfly = "audio/bgm/umib_023.opus",
    goldenslaughterer = "audio/bgm/umib_024.opus",
    worldend_bp = "audio/bgm/umib_025.opus",
    the_witch_of_the_painting = "audio/bgm/umib_026.opus",
    suspicion = "audio/bgm/umib_027.opus",
    scar_in_the_score = "audio/bgm/umib_028.opus",
    core = "audio/bgm/umib_029.opus",
    minute_darkness = "audio/bgm/umib_030.opus",
    nighteyes = "audio/bgm/umib_031.opus",
    closed_my_heart = "audio/bgm/umib_032.opus",
    requiem = "audio/bgm/umib_033.opus",
    mind = "audio/bgm/umib_034.opus",
    worldend = "audio/bgm/umib_035.opus",
    play = "audio/bgm/umib_036.opus",
    system0 = "audio/bgm/umib_037.opus",
    voiceless = "audio/bgm/umib_038.opus",
    dead_angle = "audio/bgm/umib_039.opus",
    organ_short_600_million_in_c_minor = "audio/bgm/umib_040.opus",
    prison_strip = "audio/bgm/umib_041.opus",
    string_quartet_1_in_g_major_allegro = "audio/bgm/umib_042.opus",
    cage = "audio/bgm/umib_043.opus",
    golden_sneer = "audio/bgm/umib_044.opus",
    scorpion_guts = "audio/bgm/umib_045.opus",
    lifes_end_verc = "audio/bgm/umib_046.opus",
    answer = "audio/bgm/umib_047.opus",
    answer_short = "audio/bgm/umib_048.opus",
    melody_inst_ver = "audio/bgm/umib_049.opus",
    red_dread = "audio/bgm/umib_050.opus",
    moon = "audio/bgm/umib_051.opus",
    where = "audio/bgm/umib_052.opus",
    dread_of_the_grave = "audio/bgm/umib_053.opus",
    worldend_dominator = "audio/bgm/umib_054.opus",
    black_liliana = "audio/bgm/umib_055.opus",
    rest = "audio/bgm/umib_056.opus",
    end_of_a_daydream = "audio/bgm/umib_057.opus",
    melody = "audio/bgm/umib_058.opus",
    over_the_sky = "audio/bgm/umib_059.opus",
    sunny_spot = "audio/bgm/umib_060.opus",
    the_candles_dance = "audio/bgm/umib_061.opus",
    distant = "audio/bgm/umib_062.opus",
    psy_chorus = "audio/bgm/umib_063.opus",
    far = "audio/bgm/umib_064.opus",
    red_shoes_fake = "audio/bgm/umib_065.opus",
    mother = "audio/bgm/umib_066.opus",
    haze = "audio/bgm/umib_067.opus",
    dancing_pipe = "audio/bgm/umib_068.opus",
    dread_of_the_grave_more_fear = "audio/bgm/umib_069.opus",
    organ_short_200_million_in_c_minor = "audio/bgm/umib_070.opus",
    rhythm_changer = "audio/bgm/umib_071.opus",
    happiness_of_marionette_bonus = "audio/bgm/umib_072.opus",
    happiness_of_marionette = "audio/bgm/umib_073.opus",
    dance_of_the_moon_rabbits = "audio/bgm/umib_074.opus",
    melting_away = "audio/bgm/umib_075.opus",
    soul_of_soul = "audio/bgm/umib_076.opus",
    miragecoordinator = "audio/bgm/umib_077.opus",
    prison = "audio/bgm/umib_078.opus",
    thanks_for_being_born = "audio/bgm/umib_079.opus",
    wings = "audio/bgm/umib_080.opus",
    paradise_lost = "audio/bgm/umib_081.opus",
    wingless = "audio/bgm/umib_082.opus",
    activepain = "audio/bgm/umib_083.opus",
    dread_of_the_grave_rhythm_ver = "audio/bgm/umib_084.opus",
    eternity = "audio/bgm/umib_085.opus",
    over = "audio/bgm/umib_086.opus",
    like_the_gale = "audio/bgm/umib_087.opus",
    f_style = "audio/bgm/umib_088.opus",
    monochrome_clock = "audio/bgm/umib_089.opus",
    apathy = "audio/bgm/umib_090.opus",
    mystic_forest = "audio/bgm/umib_091.opus",
    sakutarous_adventure = "audio/bgm/umib_092.opus",
    parallel = "audio/bgm/umib_093.opus",
    five_hundred_ninety_nine_million_ruins = "audio/bgm/umib_095.opus",
    happy_maria_instrumental = "audio/bgm/umib_096.opus",
    surrounding = "audio/bgm/umib_097.opus",
    open_fire = "audio/bgm/umib_098.opus",
    death_from_stupefaction = "audio/bgm/umib_099.opus",
    mortal_stampede = "audio/bgm/umib_100.opus",
    victima_propiciatoria = "audio/bgm/umib_101.opus",
    revolt = "audio/bgm/umib_102",
    purgatory_catastrophe_rhapsodie = "audio/bgm/umib_103.opus",
    happy_maria = "audio/bgm/umib_104.opus",
    dive_to_emergency = "audio/bgm/umib_105.opus",
    _dir = "audio/bgm/umib_106.opus",
    endless_nine = "audio/bgm/umib_107.opus",
    dreamenddischarger = "audio/bgm/umib_108.opus",
    discotheque = "audio/bgm/umib_109.opus",
    twirl = "audio/bgm/umib_110.opus",
    future = "audio/bgm/umib_111.opus",
    deep_blue_jeer = "audio/bgm/umib_112.opus",
    the_great_detective_knows = "audio/bgm/umib_113.opus",
    smileless_soiree = "audio/bgm/umib_114.opus",
    one = "audio/bgm/umib_115.opus",
    spiral = "audio/bgm/umib_116.opus",
    string_trio_600_million_in_f_sharp_minor = "audio/bgm/umib_117.opus",
    totenblume = "audio/bgm/umib_118.opus",
    justice = "audio/bgm/umib_119.opus",
    aci_l = "audio/bgm/umib_120.opus",
    predator = "audio/bgm/umib_121.opus",
    proud_dust = "audio/bgm/umib_122.opus",
    hello_your_dream = "audio/bgm/umib_123.opus",
    a_lonely_deep_sea_fish = "audio/bgm/umib_124.opus",
    the_girls_witch_hunt = "audio/bgm/umib_125.opus",
    patchwork_chimera = "audio/bgm/umib_126.opus",
    discolor = "audio/bgm/umib_127.opus",
    resurrectedreplayer = "audio/bgm/umib_128.opus",
    final_answer = "audio/bgm/umib_129.opus",
    light = "audio/bgm/umib_130.opus",
    bread_of_life = "audio/bgm/umib_131.opus",
    promise = "audio/bgm/umib_132.opus",
    tomorrow = "audio/bgm/umib_133.opus",
    wings_ver_hope = "audio/bgm/umib_134.opus",
    fake_gray_smile = "audio/bgm/umib_135.opus",
    eternal_chains = "audio/bgm/umib_136.opus",
    love_examination = "audio/bgm/umib_137.opus",
    instant = "audio/bgm/umib_138.opus",
    look_back = "audio/bgm/umib_139.opus",
    blue_butterfly = "audio/bgm/umib_140.opus",
    my_dear = "audio/bgm/umib_141.opus",
    something_s_up_going_down = "audio/bgm/umib_142.opus",
    rog_limitation = "audio/bgm/umib_143.opus",
    waltz_op_34 = "audio/bgm/umib_144.opus",
    alive = "audio/bgm/umib_145.opus",
    birth_of_new_witch_inst = "audio/bgm/umib_146.opus",
    ruriair = "audio/bgm/umib_147.opus",
    engage_of_marionette = "audio/bgm/umib_148.opus",
    life = "audio/bgm/umib_149.opus",
    loreley = "audio/bgm/umib_150.opus",
    the_sin = "audio/bgm/umib_151.opus",
    the_first_and_the_last = "audio/bgm/umib_152.opus",
    anti_demon_sequentia = "audio/bgm/umib_153.opus",
    battle_field = "audio/bgm/umib_154.opus",
    rebirth = "audio/bgm/umib_155.opus",
    the_way = "audio/bgm/umib_156.opus",
    liberatedliberator = "audio/bgm/umib_157.opus",
    thanks_for_all_people = "audio/bgm/umib_158.opus",
    infant_queen_bee = "audio/bgm/umib_159.opus",
    birth_of_new_witch_short_ver = "audio/bgm/umib_160.opus",
    fishyaroma = "audio/bgm/umib_161.opus",
    le4_octobre = "audio/bgm/umib_162.opus",
    ld_circulation = "audio/bgm/umib_163.opus",
    reflection_call = "audio/bgm/umib_164.opus",
    rain = "audio/bgm/umib_165.opus",
    _7_weights = "audio/bgm/umib_166.opus",
    fall = "audio/bgm/umib_167.opus",
    bore_ral = "audio/bgm/umib_168.opus",
    ballade_continuer = "audio/bgm/umib_169.opus",
    song_without_a_name_ver_2007_inst = "audio/bgm/umib_170.opus",
    lie_alaia = "audio/bgm/umib_171.opus",
    golden_nocturne_inst = "audio/bgm/umib_172.opus",
    far_flat = "audio/bgm/umib_173.opus",
    toybox = "audio/bgm/umib_174.opus",
    terminal_entrance = "audio/bgm/umib_175.opus",
    puppet_show = "audio/bgm/umib_176.opus",
    she_end = "audio/bgm/umib_177.opus",
    song_without_a_name_full_inst = "audio/bgm/umib_179.opus",
    the_end_of_the_world = "audio/bgm/umib_180.opus",
    goddess_gardena = "audio/bgm/umib_181.opus",
    ridicule = "audio/bgm/umib_183.opus",
    yomotsu_hirasaka_corruption = "audio/bgm/umib_184.opus",
    the_executioner = "audio/bgm/umib_185.opus",
    song_without_a_name_ver_sakura_ed_size = "audio/bgm/umib_186.opus",
    stuffed_animal = "audio/bgm/umib_187.opus",
    bizarre_divertimento = "audio/bgm/umib_188.opus",
    en_counse = "audio/bgm/umib_190.opus",
    lix_axil = "audio/bgm/umib_191.opus",
    revelations_inst = "audio/bgm/umib_192.opus",
    flying = "audio/bgm/umib_193.opus",
    lastendconductor = "audio/bgm/umib_194.opus",
    revelations = "audio/bgm/umib_195.opus",
    cocoon_of_white_dreams = "audio/bgm/umib_240.opus",
    when_the_seagulls_cry = "audio/bgm/umib_241.opus",
    suisui_sweets = "audio/bgm/umib_1000.opus",
    bring_the_fate = "audio/bgm/umib_1010.opus",
    bring_the_fate_ver_chiru = "audio/bgm/umib_1013.opus",
    tsurupettan = "audio/bgm/umib_94.opus",
    system0_original_version = "audio/bgm/umib_1011.opus",
    igreja_of_echoing_vows = "audio/bgm/umib_1012.opus",
    inannas_dream = "audio/bgm/umib_1014.opus",
    the_witch_of_occultics = "audio/bgm/umib_1017.opus",
    the_pithos_in_the_fog = "audio/bgm/umib_1018.opus",


    ## Add them to the dictionary
    music_dictionary = {
        thunberg_lily : "Thunberg Lily",
        door_of_summer : "Door of Summer",
        hane : "HANE Feathers",
        ride_on : "Ride on",
        sea : "sea",
        hour_of_darkness : "Hour of Darkness",
        novelette : "Novelette",
        hope : "hope",
        white_shadow : "White Shadow",
        steady_pace : "steady pace",
        towering_cloud_in_summer : "Towering cloud in summer",
        moonlit_night : "Moonlit Night",
        rose : "Rose",
        at_deaths_door : "At Death’s Door",
        hells_halls : "Hell’s Halls",
        fortitude : "Fortitude",
        witch_in_gold_cembalo : "witch in gold(cembalo)",
        beckoning : "Beckoning",
        fishy_aroma : "Fishy Aroma",
        stupefaction : "stupefaction",
        praise : "praise",
        bgm_pass : "Pass",
        butterfly : "butterfly",
        goldenslaughterer : "goldenslaughterer",
        worldend_bp : "Worldend(bp)",
        the_witch_of_the_painting : "The Witch of the Painting",
        suspicion : "suspicion",
        scar_in_the_score : "Scar in the Score",
        core : "Core",
        minute_darkness : "minute darkness",
        nighteyes : "nighteyes",
        closed_my_heart : "Closed My Heart",
        requiem : "Requiem",
        mind : "mind",
        worldend : "Worldend",
        _play : "play",
        system0 : "system0",
        voiceless : "Voiceless",
        dead_angle : "dead angle",
        organ_short_600_million_in_c_minor : "Organ Short #600 Million in C Minor",
        prison_strip : "Prison STRIP",
        string_quartet_1_in_g_major_allegro : "String Quartet #1 in G Major — I.Allegro",
        cage : "cage",
        golden_sneer : "Golden Sneer",
        scorpion_guts : "Scorpion Guts",
        lifes_end_verc : "Life's End (VerC)",
        answer : "Answer",
        answer_short : "Answer short",
        melody_inst_ver : "Melody inst.ver",
        red_dread : "Red Dread",
        moon : "moon",
        where : "where",
        dread_of_the_grave : "Dread of the grave",
        worldend_dominator : "Worldend dominator",
        black_liliana : "Black Liliana",
        rest : "Rest",
        end_of_a_daydream : "End of a Daydream",
        melody : "Melody",
        over_the_sky : "Over the sky",
        sunny_spot : "sunny spot",
        the_candles_dance : "The Candles Dance",
        distant : "Distant",
        psy_chorus : "psy-chorus",
        far : "far",
        red_shoes_fake : "red shoes FAKE",
        mother : "mother",
        haze : "haze",
        dancing_pipe : "Dancing Pipe",
        dread_of_the_grave_more_fear : "Dread of the grave -More fear-",
        organ_short_200_million_in_c_minor : "Organ Short #200 Million in C Minor",
        rhythm_changer : "rhythm-changer",
        happiness_of_marionette_bonus : "happiness of marionette bonus",
        happiness_of_marionette : "happiness of marionette",
        dance_of_the_moon_rabbits : "Dance of the Moon Rabbits",
        melting_away : "Melting Away",
        soul_of_soul : "Soul of Soul",
        miragecoordinator : "Miragecoordinator",
        prison : "Prison",
        thanks_for_being_born : "Thanks for Being Born",
        wings : "Wings",
        paradise_lost : "Paradise Lost",
        wingless : "Wingless",
        activepain : "Activepain",
        dread_of_the_grave_rhythm_ver : "Dread of the Grave -Rhythm Ver-",
        eternity : "Eternity",
        over : "Over",
        like_the_gale : "Like the Gale",
        f_style : "F Style",
        monochrome_clock : "Monochrome Clock",
        apathy : "Apathy",
        mystic_forest : "Mystic Forest",
        sakutarous_adventure : "Sakutarou's Adventure",
        parallel : "Parallel",
        five_hundred_ninety_nine_million_ruins : "599 Million Ruins",
        happy_maria_instrumental : "Happy Maria (Instrumental)",
        surrounding : "Surrounding",
        open_fire : "Open Fire",
        death_from_stupefaction : "Death from Stupefaction",
        mortal_stampede : "Mortal Stampede",
        victima_propiciatoria : "Victima Propiciatoria",
        revolt : "Revolt",
        purgatory_catastrophe_rhapsodie : "Purgatory Catastrophe Rhapsodie",
        happy_maria : "Happy Maria",
        dive_to_emergency : "Dive to Emergency",
        _dir : "dir",
        endless_nine : "Endless Nine",
        dreamenddischarger : "Dreamenddischarger",
        discotheque : "Discotheque",
        twirl : "Twirl",
        future : "Future",
        deep_blue_jeer : "Deep Blue Jeer",
        the_great_detective_knows : "The Great Detective Knows",
        smileless_soiree : "Smileless Soiree",
        one : "One",
        spiral : "Spiral",
        string_trio_600_million_in_f_sharp_minor : "String Trio #600 Million in F-Sharp Minor",
        totenblume : "Totenblume",
        justice : "Justice",
        aci_l : "ACI-L",
        predator : "Predator",
        proud_dust : "Proud-dust",
        hello_your_dream : "hello your dream",
        a_lonely_deep_sea_fish : "A Lonely Deep-Sea Fish",
        the_girls_witch_hunt : "The Girls's Witch Hunt",
        patchwork_chimera : "Patchwork Chimera",
        discolor : "Discolor",
        resurrectedreplayer : "Resurrectedreplayer",
        final_answer : "Final Answer",
        light : "Light",
        bread_of_life : "Bread of Life",
        promise : "Promise",
        tomorrow : "Tomorrow",
        wings_ver_hope : "WINGS(Ver.Hope)",
        fake_gray_smile : "Fake Gray Smile",
        eternal_chains : "Eternal Chains",
        love_examination : "Love Examination",
        instant : "Instant",
        look_back : "Look Back",
        blue_butterfly : "Blue Butterfly",
        my_dear : "my dear",
        somethings_up_going_down : "Something’s Up & Going Down",
        rog_limitation : "rog-limitation",
        waltz_op34 : "Waltz Op.34",
        alive : "ALIVE",
        birth_of_new_witch_inst : "birth of new witch(inst)",
        ruriair : "ruriair",
        engage_of_marionette : "Engage of marionette",
        life : "Life",
        loreley : "Loreley",
        the_sin : "The Sin",
        the_first_and_the_last : "The first and The last",
        anti_demon_sequentia : "Anti-Demon Sequentia",
        battle_field : "battle field",
        rebirth : "Rebirth",
        the_way : "The Way",
        liberatedliberator : "liberatedliberator",
        thanks_for_all_people : "Thanks for all people",
        infant_queen_bee : "Infant Queen Bee",
        birth_of_new_witch_short_ver : "birth of new witch(Short Ver)",
        fishyaroma : "FISHYAROMA",
        le4_octobre : "le4-octobre",
        l_d_circulation : "l&d-circulation",
        reflection_call : "reflection-call",
        rain : "rain",
        _7_weights : "7-weights",
        fall : "fall",
        bore_ral : "bore-ral",
        ballade_continuer : "ballade-continuer",
        song_without_a_name_ver2007_inst : "Song without a name ver.2007 inst",
        lie_alaia : "lie-alaia",
        golden_nocturne_inst : "Golden Nocturne(inst)",
        far_flat : "far(flat)",
        toybox : "Toybox",
        terminal_entrance : "terminal entrance",
        puppet_show : "Puppet Show",
        s_he_end : "s/he-end",
        song_without_a_name_full_inst : "Song without a name full-inst",
        the_end_of_the_world : "The End Of The World",
        goddess_gardena : "goddess-gardena",
        ridicule : "ridicule",
        yomotsu_hirasaka_corruption : "Yomotsu Hirasaka Corruption",
        the_executioner : "the executioner",
        song_without_a_name_ver_sakura_ed_size : "Song without a name ver.sakura ED-size",
        stuffed_animal : "Stuffed Animal",
        bizarre_divertimento : "Bizarre Divertimento",
        en_counse : "en-counse",
        lixAxil : "lixAxil",
        revelations_inst : "Revelations(inst)",
        flying : "Flying",
        lastendconductor : "lastendconductor",
        revelations : "Revelations",
        cocoon_of_white_dreams_ricordando_il_passato : "Cocoon of White Dreams -Ricordando il passato-",
        when_the_seagulls_cry : "When the Seagulls Cry",
        suisui_sweets : "SuiSui☆SWEETS(^-^)",
        bring_the_fate : "Bring The Fate",
        bring_the_fate_ver_chiru : "Bring The Fate(Ver chiru)",
        tsurupettan : "Tsurupettan",
        system0_original_version : "system0(Original Version)",
        igreja_of_echoing_vows : "Igreja of Echoing Vows",
        inannas_dream : "Inanna's Dream",
        the_witch_of_occultics : "The Witch of Occultics",
        the_pithos_in_the_fog : "The Pithos in the Fog"
}


init python:
    ## It should show a screen when a song is playing.
    def play_music(music_alias,fade=0):
        renpy.music.play(music_alias,fadein=fade)
        renpy.show_screen("showsong")
