define narrator = Character(show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag=None, show_two_window=False, window_xminimum=1420, window_xmaximum=1800, window_yoffset=2, window_background=Frame("gui/frame_[persistent.textbox].png", 25, 25))

define bea = Character('Beatrice', what_prefix="“", what_suffix="”", image="bea", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="bea")
define kin = Character('Ushiromiya Kinzo', what_prefix="“", what_suffix="”", image="kin", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="kin")
define cla = Character('Ushiromiya Krauss', what_prefix="“", what_suffix="”", image="cla", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="cla")
define nat = Character('Ushiromiya Natsuhi', what_prefix="“", what_suffix="”", image="nat", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="nat")
define jes = Character('Ushiromiya Jessica', what_prefix="“", what_suffix="”", image="jes", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="jes")
define eva = Character('Ushiromiya Eva', what_prefix="“", what_suffix="”", image="eva", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="eva")
define hid = Character('Ushiromiya Hideyoshi', what_prefix="“", what_suffix="”", image="hid", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="hid")
define geo = Character('Ushiromiya George', what_prefix="“", what_suffix="”", image="geo", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="geo")
define rud = Character('Ushiromiya Rudolf', what_prefix="“", what_suffix="”", image="rud", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="rud")
define kir = Character('Ushiromiya Kyrie', what_prefix="“", what_suffix="”", image="kir", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="kir")
define but = Character('Ushiromiya Battler', what_prefix="“", what_suffix="”", image="but", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="but")
define mar = Character('Ushiromiya Maria', what_prefix="“", what_suffix="”", image="mar", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="mar")
define ros = Character('Ushiromiya Rosa', what_prefix="“", what_suffix="”", image="ros", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="ros")
define nan = Character('Nanjo Terumasa', what_prefix="“", what_suffix="”", image="nan", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="nan")
define gen = Character('Ronoue Genji', what_prefix="“", what_suffix="”", image="gen", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="gen")
define sha = Character('Shannon', what_prefix="“", what_suffix="”", image="sha", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="sha")
define kan = Character('Kanon', what_prefix="“", what_suffix="”", image="kan", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="kan")
define goh = Character('Gohda Toshiro', what_prefix="“", what_suffix="”", image="goh", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="goh")
define kum = Character('Chiyo Kumasawa', what_prefix="“", what_suffix="”", image="kum", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="kum")
define lam = Character('Lambdadelta', what_prefix="“", what_suffix="”", image="lam", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="lam")
define ber = Character('Bernkastel', what_prefix="“", what_suffix="”", image="ber", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="ber")
define ron = Character('Ronove', what_prefix="“", what_suffix="”", image="ron", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="ron")
define wal = Character('Virgillia', what_prefix="“", what_suffix="”", image="wal", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="wal")
define gap = Character('Gaap', what_prefix="“", what_suffix="”", image="gap", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="gap")
define luc = Character('Lucifer', what_prefix="“", what_suffix="”", image="luc", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="luc")
define lev = Character('Leviathan', what_prefix="“", what_suffix="”", image="lev", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="lev")
define sat = Character('Satan', what_prefix="“", what_suffix="”", image="sat", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="sat")
define bel = Character('Belphegor', what_prefix="“", what_suffix="”", image="bel", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="bel")
define mam = Character('Mammon', what_prefix="“", what_suffix="”", image="mam", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="mam")
define bee = Character('Beelzebub', what_prefix="“", what_suffix="”", image="bee", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="bee")
define asm = Character('Asmodeus', what_prefix="“", what_suffix="”", image="asm", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="asm")
define fea = Character('Featherine', what_prefix="“", what_suffix="”", image="fea", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="fea")
define ev1 = Character('EVA-Beatrice', what_prefix="“", what_suffix="”", image="ev1", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="ev1")
define wel = Character('Virgilius', what_prefix="“", what_suffix="”", image="wel", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="wel")
define zep = Character('Zepar', what_prefix="“", what_suffix="”", image="zep", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="zep")
define fur = Character('Furfur', what_prefix="“", what_suffix="”", image="fur", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="fur")
define fla = Character('Flaurus', what_prefix="“", what_suffix="”", image="fla", show_slow_effect = slow_fade, show_slow_effect_delay = 0.4, voice_tag="fla")
define ntxt = Character(show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, kind=nvl, voice_tag=None)

image bea_bri= Breakup("bea", 5.0, True, BreakupMode(0))
image bea_briq= Breakup("bea", 1.0, True, BreakupMode(0))
image bea_bro= Breakup("bea", 5.0, False, BreakupMode(0))
image bea_broq= Breakup("bea", 1.0, False, BreakupMode(0))


