## ADV
define bea = Character('BEATRICE', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="bea", image="bea")
define kin = Character('Ushiromiya Kinzo', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="kin", image="kin")
define cla = Character('Ushiromiya Krauss', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="cla", image="cla")
define nat = Character('Ushiromiya Natsuhi', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="nat", image="nat")
define jes = Character('Ushiromiya Jessica', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="jes", image="jes")
define eva = Character('Ushiromiya Eva', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="eva", image="eva")
define hid = Character('Ushiromiya Hideyoshi', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="hid", image="hid")
define geo = Character('Ushiromiya George', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="geo", image="geo")
define rud = Character('Ushiromiya Rudolf', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="rud", image="rud")
define kir = Character('Ushiromiya Kyrie', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="kir", image="kir")
define but = Character('Ushiromiya Battler', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="but", image="but")
define mar = Character('Ushiromiya Maria', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="mar", image="mar")
define ros = Character('Ushiromiya Rosa', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="ros", image="ros")
define nan = Character('Nanjo Terumasa', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="nan", image="nan")
define gen = Character('Ronoue Genji', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="gen", image="gen")
define sha = Character('Shannon', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="sha", image="sha")
define kan = Character('Kanon', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="kan", image="kan")
define goh = Character('Gohda Toshiro', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="goh", image="goh")
define kum = Character('Chiyo Kumasawa', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="kum", image="kum")
define lam = Character('LAMBDADELTA', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="lam", image="lam")
define ber = Character('BERNKASTEL', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="ber", image="ber")
define ron = Character('Ronove', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="ron", image="ron")
define wal = Character('VIRGILIA', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="wal", image="wal")
define gap = Character('Gaap', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="gap", image="gap")
define luc = Character('Lucifer', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="luc", image="luc")
define lev = Character('Leviathan', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="lev", image="lev")
define sat = Character('Satan', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="sat", image="sat")
define bel = Character('Belphegor', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="bel", image="bel")
define mam = Character('Mammon', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="mam", image="mam")
define bee = Character('Beelzebub', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="bee", image="bee")
define asm = Character('Asmodeus', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="asm", image="asm")
define eri = Character('Furudo Erika', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="eri", image="eri")
define fea = Character('FEATHERINE', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="fea", image="fea")
define ev1 = Character('EVA-BEATRICE', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="ev1", image="ev1")
define wel = Character('Virgilius', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="wel", image="wel")
define zep = Character('Zepar', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="zep", image="zep")
define fur = Character('Furfur', what_prefix="“", what_suffix="”", show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag="fur", image="fur")
define narrator = Character(show_slow_effect = slow_fade, show_slow_effect_delay = 0.2, voice_tag=None, show_two_window=False, window_xminimum=1420, window_xmaximum=1800, window_yoffset=2, window_background=Frame("gui/frame_[persistent.textbox].png", 25, 25))

