image bea_01:
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/2.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/1.png"
    .05
    "/sprites/bea/[bea_pose]/[bea_face]/0.png"
